In [35]:
import torch
import torch_scatter
import numpy as np

In [48]:
#model = torch.jit.load("../torchscript/no_threshold/gnn.pt")
model = torch.jit.load("../torchscript/no_threshold/filter.pt")

In [49]:
x = torch.rand((20,3))
x

tensor([[0.4582, 0.5648, 0.9673],
        [0.4079, 0.8371, 0.3463],
        [0.3507, 0.1877, 0.1141],
        [0.3838, 0.4848, 0.7349],
        [0.3014, 0.0262, 0.4024],
        [0.3447, 0.6215, 0.9172],
        [0.8655, 0.1902, 0.6670],
        [0.9797, 0.7645, 0.4028],
        [0.0526, 0.1606, 0.6931],
        [0.0565, 0.8868, 0.8640],
        [0.8592, 0.4237, 0.7373],
        [0.1800, 0.1984, 0.8857],
        [0.5016, 0.8452, 0.3239],
        [0.8475, 0.7163, 0.0047],
        [0.2893, 0.5242, 0.8736],
        [0.7658, 0.4856, 0.7386],
        [0.6968, 0.4936, 0.3177],
        [0.4470, 0.2911, 0.7224],
        [0.1121, 0.3758, 0.5710],
        [0.2928, 0.6747, 0.9905]])

In [50]:
edge_index = torch.randint(0,20,(2,10))
edge_index

tensor([[ 6, 11, 16, 16,  9, 19, 11, 13, 15,  1],
        [ 9, 12,  9, 14,  0, 18,  3, 11, 18, 12]])

In [51]:
x[edge_index[:,0]]

tensor([[0.8655, 0.1902, 0.6670],
        [0.0565, 0.8868, 0.8640]])

In [52]:
out = model(x, edge_index).sigmoid()
np.sort(out.detach())

array([0.0017111 , 0.00488361, 0.0056776 , 0.01512597, 0.02566504,
       0.08410568, 0.10118195, 0.3528163 , 0.89250934, 0.98971635],
      dtype=float32)

In [53]:
xroll = torch.roll(x,1,dims=0)

In [54]:
edge_index_roll = (edge_index + 1) % 20
edge_index_roll

tensor([[ 7, 12, 17, 17, 10,  0, 12, 14, 16,  2],
        [10, 13, 10, 15,  1, 19,  4, 12, 19, 13]])

In [55]:
xroll[edge_index_roll[:,0]]

tensor([[0.8655, 0.1902, 0.6670],
        [0.0565, 0.8868, 0.8640]])

In [56]:
out = model(xroll, edge_index_roll).sigmoid()
np.sort(out.detach())

array([0.0017111 , 0.00488361, 0.0056776 , 0.01512597, 0.02566504,
       0.08410568, 0.10118195, 0.3528163 , 0.89250934, 0.98971635],
      dtype=float32)